MVCShoppingCart/Models/Product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MVCShoppingCart.Models
{
    public class Product
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ProductId { get; set; }

        [Required]
        [Display(Name="Product")]
        public string Name { get; set; }

        public string Description { get; set; }

        public string ThumbnailImagePath { get; set; }
        
        [Required]
        public int Quantity { get; set; }

        [Required]
        public decimal Price { get; set; }

        [Required]
        public decimal Cost { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime PurchaseDate { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime? SoldDate { get; set; }

        public int? CategoryId { get; set; }

        public virtual Category Category { get; set; }

        public int? StoreManagerId { get; set; }

        public virtual StoreManager StoreManager { get; set; }

        public virtual List<Image> Images { get; set; }
    }
}

MVCShoppingCart/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVCShoppingCart.DAL;
using MVCShoppingCart.Models;
using MVCShoppingCart.Logic;
using MVCShoppingCart.ViewModel;

namespace MVCShoppingCart.Controllers
{
    public class ProductsController : Controller
    {
        // GET: Products
        public ActionResult Index()
        {
            var productService = new ProductLogic();
            var productListVM = new List<ProductListVM>();
            productListVM = productService.GetProductListVM();
            
            return View(productListVM);
        }

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var productService = new ProductLogic();
            Product product = productService.FindProduct(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }
    }
}

MVCShoppingCart/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCShoppingCart.Models;
using MVCShoppingCart.Logic;
using MVCShoppingCart.ViewModel;

namespace MVCShoppingCart.Controllers
{
    public class ShoppingCartController : Controller
    {
        // GET: ShoppingCart
        public ActionResult Index()
        {
            var cart = ShoppingCartLogic.GetCart(this.HttpContext);

            var CartViewModel = new ShoppingCartVM
            {
                CartItems = cart.GetCartItems(),
                CartSubTotal = cart.GetSubtotal(),
                CartSalesTax = cart.GetSalesTax(),
                CartTotal = cart.GetTotal(),
            };
            return View(CartViewModel);
        }

        public ActionResult AddToCart(int id)
        {
            var productService = new ProductLogic();
            var productAdded = productService.FindProduct(id);

            ShoppingCartLogic cart = ShoppingCartLogic.GetCart(this.HttpContext);
            cart.AddToCart(productAdded);

            return RedirectToAction("Index");
        }

        //AJAX post
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            var cart = ShoppingCartLogic.GetCart(this.HttpContext);

            var shoppingCart = new ShoppingCartLogic();
            int productId = shoppingCart.GetCartItemProductId(id);
            var productService = new ProductLogic();
            Product productToRemove = productService.FindProduct(productId);

            int itemCount = cart.RemoveFromCart(id);

            var removeViewModel = new ShoppingCartRemoveVM
            {
                Message = Server.HtmlEncode(productToRemove.Name) +
                    " has been removed from your shopping cart.",
                CartCount = cart.GetCount(),
                CartSubTotal = cart.GetSubtotal(),
                CartSalesTax = cart.GetSalesTax(),
                CartTotal = cart.GetTotal(),
                ItemCount = itemCount,
                DeleteId = id,
            };

            return Json(removeViewModel);
        }

        public ActionResult CustomerInfo()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CustomerInfo([Bind(Include = "FirstName,LastName,StreetAddress1,StreetAddress2,City,State,PostalCode,Country,Email,Phone")] Customer customer)
        {
            var customerLogic = new CustomerLogic();
            customerLogic.CreateNewCustomer(customer);
            return RedirectToAction("Payment");
        }

        public ActionResult Payment()
        {
            return View();
        }

        public ActionResult Checkout()
        {
            return View();
        }
    }
}

MVCShoppingCart/Views/Products/Details.cshtml
@model MVCShoppingCart.Models.Product

@{
    ViewBag.Title = "Details";
}

<h2>@Html.DisplayFor(model => model.Name)</h2>

<hr />

<div class="container">
    <p>
        <img alt="@Model.Name" src="@Url.Content(Model.ThumbnailImagePath)" />
    </p>

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

    </dl>
</div>
<p>
    <a class="btn btn-default" href="@Url.Action("AddToCart", "ShoppingCart", new { id = Model.ProductId })">Add to Cart</a>
    <a class="btn btn-primary" href="@Url.Action("Index","Products")">Back to List</a>
</p>

MVCShoppingCart/Views/Products/Index.cshtml
@model IEnumerable<MVCShoppingCart.ViewModel.ProductListVM>

@{
    ViewBag.Title = "Browse Products";
}

<h2>Products</h2>
<hr/>

<ul class="list-unstyled">
    @foreach (var item in Model)
    {
        <li class="col-lg-3 col-md-3 col-sm-2 col-xs-1 container">
            <a href="@Url.Action("Details", new {id = item.ProductId })">
                <img src="@Url.Content(item.ThumbnailImagePath)" /> 
                <h4 class="control-label">@item.Name</h4>
                <h5>@item.Price</h5>
                <p>
                    <a class="btn btn-default btn-sm" href="@Url.Action("AddToCart", "ShoppingCart", new {id = item.ProductId })">Add to Cart</a>
                </p>
            </a>
        </li>
    }
</ul>